name: Deploy to S3

on:
  push:
    branches:
      - main  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.10.0'  

    - name: Install dependencies
      run: npm install

    - name: Build the Astro project
      run: npm run build

    - name: Install AWS CLI
      run: sudo apt-get install awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Deploy to S3
      run: |
        aws s3 sync ./dist/ s3://synthythings-frontend --delete
        aws s3 website s3://synthythings-frontend --index-document index.html --error-document index.html
